theme: minima

title: config title
author: config author
description: config description, a long long description

email: email@example.com

minima:
  social_links:
    twitter: jekyllrb
    github: jekyll
    facebook: jekyll
